version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: sitetour-postgres
    restart: always
    environment:
      POSTGRES_DB: sitetour
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - sitetour_data:/var/lib/postgresql/data

volumes:
  sitetour_data: